name: Deploy
description: Build and deploy to Railway

inputs:
  railway_project_id:
    required: true
  railway_environment_id:
    required: true
  railway_service_id:
    required: true
  railway_token:
    required: true

runs:
  using: composite
  steps:
    - uses: merkaly-io/actions/setup@master

    - run: pnpm build
      shell: bash

    - run: |
        pnpm dlx @railway/cli up \
          --ci \
          --project "$RAILWAY_PROJECT_ID" \
          --environment "$RAILWAY_ENVIRONMENT_ID" \
          --service "$RAILWAY_SERVICE_ID" \
          -m "${{ github.ref_name }}"
      shell: bash
      env:
        RAILWAY_TOKEN: ${{ inputs.railway_token }}
        RAILWAY_PROJECT_ID: ${{ inputs.railway_project_id }}
        RAILWAY_ENVIRONMENT_ID: ${{ inputs.railway_environment_id }}
        RAILWAY_SERVICE_ID: ${{ inputs.railway_service_id }}
