name: Setup
description: Checkout, setup Node, and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        fetch-tags: true

    - run: corepack enable
      shell: bash

    - uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: pnpm

    - run: pnpm install --frozen-lockfile
      shell: bash
